Szyntos/oops

frontend/src/api/points.ts
frontend/src/utils/types.ts

Change the Points type to contain nested objects instead of bare IDs.

introduce upgrated points type

---

backend/hasura/metadata/databases/mydatabase/tables/public_chest_history.yaml

Added chest-history insert for teacher cuz it can be done with insert, no custom mutation needed

Added chest-history insert for teacher

---

frontend/src/components/form/NumberInput.tsx
frontend/src/components/form/SelectInput.tsx
frontend/src/components/form/form.styles.ts
frontend/src/components/form/index.tsx
frontend/src/components/index.ts
frontend/src/screens/StudentProfile/PointsForm.tsx

- add numer and select input - only those inputs that are currently in use
- preparation for styling inputs in future

[FORMS] Add components for different input tags with supporting errors

---

backend/hasura/metadata/databases/mydatabase/tables/public_users.yaml
backend/src/main/resources/db/migration/V16__add_fullName_function.sql

Users table has now a computed field fullName

Added fullName computed field to users

---

backend/docker-compose.yaml
backend/hasura/metadata/databases/mydatabase/tables/public_files.yaml
backend/hasura/metadata/databases/mydatabase/tables/public_users.yaml
backend/src/main/python/insert_data.py
backend/src/main/resources/db/migration/V21__change_current_timestamp_to_now.sql
backend/src/main/resources/db/migration/V22__create_updated_at_triggers.sql

Added a trigger for update and changed timezone of our docker

[42] Fixed timestamps

---

frontend/src/__generated__/schema.graphql
frontend/src/__generated__/schema.graphql.types.ts
frontend/src/components/PointsBar.tsx
frontend/src/components/StudentProfile/SideBar.tsx
frontend/src/components/StudentProfile/cards/CategoriesCard.tsx
frontend/src/components/StudentProfile/cards/userCard.tsx
frontend/src/components/StudentProfile/table/FilterMenu.tsx
frontend/src/components/StudentProfile/table/PointsTable.tsx
frontend/src/components/StudentProfile/table/PointsTableWithFilter.tsx
frontend/src/graphql/categoriesPoints.graphql
frontend/src/graphql/categoriesPoints.graphql.types.ts
frontend/src/hooks/StudentProfile/useStudentData.ts
frontend/src/screens/StudentProfile/StudentProfile.tsx
frontend/src/screens/StudentProfile/TeacherStudentProfile.tsx

- points bar added
- deleted lvl point bar from student card for now

[FE-8] Categories points bars

---

backend/hasura/metadata/databases/mydatabase/tables/public_levels.yaml
backend/src/main/kotlin/backend/levels/Levels.kt
backend/src/main/resources/db/migration/V23__change_maximum_points_to_non_nullable.sql

Added highest to levels in Kotlin

[53] Added highest to levels in Kotlin

---

backend/hasura/metadata/databases/mydatabase/tables/public_edition.yaml
backend/hasura/metadata/databases/mydatabase/tables/public_user_level.yaml
backend/src/main/kotlin/backend/edition/Edition.kt
backend/src/main/kotlin/backend/graphql/BonusDataFetcher.kt
backend/src/main/kotlin/backend/graphql/GroupsDataFetcher.kt
backend/src/main/kotlin/backend/graphql/PointsDataFetcher.kt
backend/src/main/kotlin/backend/groups/Groups.kt
backend/src/main/kotlin/backend/groups/GroupsRepository.kt
backend/src/main/kotlin/backend/levels/Levels.kt
backend/src/main/kotlin/backend/userGroups/UserGroups.kt
backend/src/main/kotlin/backend/userGroups/UserGroupsRepository.kt
backend/src/main/kotlin/backend/users/Users.kt
backend/src/main/kotlin/backend/users/UsersRepository.kt
backend/src/main/resources/schema/schema.graphql

To adress the issue that graphql didn't want to load appropriate objects i chose to rewrite the whole schema.graphql file.
I've split the userGroups onto seperate Kotlin class for my sanity's sake.

[56] Schema.graphql rewrite

---

backend/src/main/kotlin/backend/graphql/GroupsDataFetcher.kt
backend/src/main/resources/schema/schema.graphql

getPossibleGroupsTimeSpans(editionId: 4) {
endTime
startTime
}
getPossibleGroupsWeekdays(editionId: 4)
}

[58] Added weekday and timespan fetchers

---

backend/src/main/kotlin/backend/graphql/GroupsDataFetcher.kt
backend/src/main/kotlin/backend/graphql/UsersDataFetcher.kt

Fixed getStudentPoints and getUsersInGroupWithPoints. Just some stupid mistakes while coding at 3am

[55] Data fetchers fix

---

backend/src/main/resources/db/migration/V28__add_group_to_hall_of_fame.sql

[64] Added groups to hall of fame

---

backend/hasura/metadata/databases/mydatabase/tables/public_levels.yaml
backend/src/main/kotlin/backend/graphql/LevelsDataFetcher.kt
backend/src/main/kotlin/backend/levels/Levels.kt
backend/src/main/kotlin/backend/levels/LevelsRepository.kt
backend/src/main/resources/schema/schema.graphql

Added addLevels mutation (imageFileId is optional)
mutation MyMutation {
addLevel(editionId: 9, grade: 3.5, maximumPoints: 70, name: "NewLevel5", imageFileId:1) {
grade
highest
imageFile {
fileName
}
label
levelId
levelName
maximumPoints
minimumPoints
ordinalNumber
}
}

Added addLevels mutation

---

backend/src/main/kotlin/backend/graphql/GroupsDataFetcher.kt
backend/src/main/resources/schema/schema.graphql

Added getPossibleGroupDates
getPossibleGroupDates(editionId: 1) {
endTime
startTime
weekday
}
}

[36-2] Added getPossibleGroupDates

---

backend/src/main/kotlin/backend/graphql/UsersDataFetcher.kt
backend/src/main/kotlin/backend/groups/Groups.kt
backend/src/main/kotlin/backend/users/Users.kt
backend/src/main/python/insert_data.py
backend/src/main/python/utils/insert_levels.py
backend/src/main/resources/db/migration/V31__add_teacher_to_group.sql
backend/src/main/resources/db/migration/V32__add_group_teacher_trigger.sql
backend/src/main/resources/db/migration/V33__upgrade_user_levels_trigger.sql
backend/src/main/resources/schema/schema.graphql

```graphql
query StudentPoints($editionId: Int!, $studentId: Int!) {
getStudentPoints(editionId: $editionId, studentId: $studentId) {
level {
levelName
ordinalNumber
}
user {
firstName
indexNumber
label
nick
role
secondName
imageFile {
fileId
fileName
fileType
label
pathToFile
}
userId
userGroups {
group {
groupsId
endTime
groupName
startTime
weekday
teacher {
userId
}
}
}
}
sumOfAll
sumOfBonuses
sumOfPurePoints
subcategoryPoints {
points {
purePoints {
value
teacher {
firstName
secondName
}
}
partialBonusType {
partialValue
bonuses {
award {
awardName
}
}
}
}
subcategory {
subcategoryName
category {
categoryId
categoryName
}
}
}
}
}
```

Added teacher to group and level to getStudentPoints

---

backend/src/main/kotlin/backend/graphql/PointsDataFetcher.kt

Added check Teacher is not a teacher of student's group to addPointsMutation

Added one small check

---

backend/src/main/python/insert_data.py

Insert Data Fix - > fixed levels

Insert Data Fix

---

backend/src/main/kotlin/backend/award/Award.kt
backend/src/main/kotlin/backend/graphql/AwardsDataFetcher.kt
backend/src/main/python/requirements.txt
backend/src/main/python/utils/insert_points.py
backend/src/main/resources/schema/schema.graphql

Added addAward mutation, rounded up the values in the insert script
```graphql
mutation MyMutation {
addAward(awardName: "SówkaMiś", awardType: "ADDITIVE", categoryId: 2, maxUsages: 10, awardValue: 1) {
awardType
awardName
awardValue
}
}
```

Added addAward mutation

---

backend/build.gradle.kts
backend/setup.bat
backend/setup.sh
backend/src/main/resources/application.properties

Added WIN and MAC script
run setup.sh / setup.bat

Added WIN and MAC script

---

backend/src/main/python/config.json
backend/src/main/python/insert_data.py
backend/src/main/python/requirements.txt
backend/src/main/python/utils/insert_points.py

Added deleting photos manually to the script

Added deleting photos manually

---

backend/src/main/kotlin/backend/graphql/LevelsDataFetcher.kt
backend/src/main/resources/schema/schema.graphql

```graphql
getNeighbouringLevels(editionId: 2, studentId: 319) {
previousLevel {
ordinalNumber
levelName
levelId
}
currentLevel {
ordinalNumber
levelName
levelId
}
nextLevel {
ordinalNumber
levelName
levelId
}
}
}
```

Added getNeighbouringLevels

---

backend/src/main/kotlin/backend/graphql/UsersDataFetcher.kt

Added errors for student not in edition

Added errors for student not in edition

---

frontend/codegen.yml

Fixed issues with float8 being string

Fixed issues with float8 being string

---

backend/hasura/metadata/databases/mydatabase/tables/public_groups.yaml
backend/hasura/metadata/databases/mydatabase/tables/public_users.yaml
backend/src/main/kotlin/backend/BackendApplication.kt
backend/src/main/kotlin/backend/award/AwardRepository.kt
backend/src/main/kotlin/backend/awardEdition/AwardEditionRepository.kt
backend/src/main/kotlin/backend/chests/ChestsRepository.kt
backend/src/main/kotlin/backend/edition/EditionRepository.kt
backend/src/main/kotlin/backend/graphql/AwardEditionDataFetcher.kt
backend/src/main/kotlin/backend/graphql/AwardsDataFetcher.kt
backend/src/main/kotlin/backend/graphql/ChestHistoryDataFetcher.kt
backend/src/main/kotlin/backend/graphql/ChestsDataFetcher.kt
backend/src/main/kotlin/backend/graphql/EditionDataFetcher.kt
backend/src/main/kotlin/backend/graphql/GroupsDataFetcher.kt
backend/src/main/kotlin/backend/graphql/SubcategoriesDataFetcher.kt
backend/src/main/kotlin/backend/graphql/UsersDataFetcher.kt
backend/src/main/kotlin/backend/groups/Groups.kt
backend/src/main/kotlin/backend/groups/GroupsRepository.kt
backend/src/main/kotlin/backend/subcategories/SubcategoriesRepository.kt
backend/src/main/kotlin/backend/users/UsersRepository.kt
backend/src/main/resources/schema/schema.graphql

```graphql
addChestToUser(userId: Int!, chestId: Int!, teacherId: Int!, subcategoryId: Int!): ChestHistoryType
addChest(chestType: String!, editionId: Int!, label: String = ""): ChestType
addEdition(editionName: String!, editionYear: Int!, label: String = ""): EditionType
addGroup(editionId: Int!, groupName: String!, weekday: String!, startTime: String!,
endTime: String!, teacherId: Int!, label: String = ""): GroupType
addSubcategory(subcategoryName: String!, maxPoints: Float!, ordinalNumber: Int!,
categoryId: Int!, editionId: Int!, label: String = ""): SubcategoryType
addUser(indexNumber: Int!, nick: String!, firstName: String!,
secondName: String!, role: String!, label: String = ""): UserType
addAwardToEdition(awardId: Int!, editionId: Int!): AwardEditionType …
```

Custom inserts

---

backend/hasura/metadata/databases/mydatabase/tables/public_points.yaml
backend/hasura/metadata/databases/mydatabase/tables/public_points_history.yaml
backend/hasura/metadata/databases/mydatabase/tables/public_subcategories.yaml
backend/hasura/metadata/databases/mydatabase/tables/public_users.yaml
backend/hasura/metadata/databases/mydatabase/tables/tables.yaml
backend/src/main/kotlin/backend/graphql/BonusDataFetcher.kt
backend/src/main/kotlin/backend/graphql/PointsDataFetcher.kt
backend/src/main/kotlin/backend/pointHistory/PointHistoryRepository.kt
backend/src/main/kotlin/backend/pointHistory/PointsHistory.kt
backend/src/main/kotlin/backend/points/Points.kt
backend/src/main/resources/db/migration/V35__add_point_history_table.sql
backend/src/main/resources/schema/schema.graphql

```graphql
pointsHistory {
copiedAt
pointsHistoryId
pointsId
studentId
subcategoryId
teacherId
updatedAt
value
createdAt
label
updatedBy
}
}
```

[71] Added PointsHistory table and updatedBy

---

frontend/src/components/EditableIndicator.tsx
frontend/src/components/Groups/FilterBar/FilterOptionsSection.tsx
frontend/src/components/Groups/GroupsList/GroupCard.tsx
frontend/src/components/Students/StudentsListCard.tsx
frontend/src/graphql/groups.graphql
frontend/src/graphql/groups.graphql.types.ts
frontend/src/hooks/common/useGroupsData.tsx

https://oops2000.atlassian.net/browse/SCRUM-90

[FE-90] Add photos and editable indicator to groups list card

---

backend/src/main/kotlin/backend/awardEdition/AwardEditionRepository.kt
backend/src/main/kotlin/backend/bonuses/BonusesRepository.kt
backend/src/main/kotlin/backend/categoryEdition/CategoryEditionRepository.kt
backend/src/main/kotlin/backend/chestAward/ChestAwardRepository.kt
backend/src/main/kotlin/backend/graphql/AwardEditionDataFetcher.kt
backend/src/main/kotlin/backend/graphql/AwardsDataFetcher.kt
backend/src/main/kotlin/backend/graphql/CategoriesDataFetcher.kt
backend/src/main/kotlin/backend/graphql/CategoryEditionDataFetcher.kt
backend/src/main/kotlin/backend/graphql/ChestHistoryDataFetcher.kt
backend/src/main/kotlin/backend/graphql/ChestsAwardDataFetcher.kt
backend/src/main/kotlin/backend/graphql/ChestsDataFetcher.kt
backend/src/main/kotlin/backend/graphql/EditionDataFetcher.kt
backend/src/main/kotlin/backend/graphql/GroupsDataFetcher.kt
backend/src/main/kotlin/backend/graphql/LevelsDataFetcher.kt
backend/src/main/kotlin/backend/graphql/PhotoAssigner.kt
backend/src/main/kotlin/backend/graphql/PointsDataFetcher.kt
backend/src/main/kotlin/backend/graphql/SubcategoriesDataFetcher.kt
backend/src/main/kotlin/backend/graphql/UserGroupsDataFetcher.kt
backend/src/main/kotlin/backend/graphql/UsersDataFetcher.kt
backend/src/main/kotlin/backend/groups/Groups.kt
backend/src/main/kotlin/backend/levels/LevelsRepository.kt
backend/src/main/kotlin/backend/points/PointsRepository.kt
backend/src/main/kotlin/backend/userGroups/UserGroupsRepository.kt
backend/src/main/resources/db/migration/V31__add_teacher_to_group.sql
backend/src/main/resources/schema/schema.graphql

```graphql
addCategory(
categoryName: String!
canAddPoints: Boolean!
label: String = ""
): CategoryType
addCategoryToEdition(categoryId: Int!, editionId: Int!): CategoryEditionType
addEdition(
editionName: String!
editionYear: Int!
label: String = ""
): EditionType
addGroup(
editionId: Int!
groupName: String!
weekdayId: Int!
startTime: String!
endTime: String!
teacherId: Int!
label: String = ""
): GroupType
addSubcategory(
subcategoryName: String!
maxPoints: Float!
ordinalNumber: Int!
categoryId: Int!
editionId: Int!
label: String = ""
): SubcategoryType
addUser(
indexNumber: Int!
nick: String!
firstName: String!
secondName: String!
role: String!
label: String = ""
): UserType
generateSubcategories(
editionId: Int!
categoryId: Int!
subcategoryPrefix: String!
subcategoryCount: Int! …
```

Added edits and removes for Coordinator

---

backend/src/main/kotlin/backend/graphql/GroupsDataFetcher.kt
backend/src/main/resources/schema/schema.graphql

```graphql
getGroupsInEdition(editionId: 3, teacherId: 1) {
canEdit
owns
group {
groupsId
}
}
}
```

[99] Added getGroupsInEdition

---

frontend/src/__generated__/schema.graphql
frontend/src/__generated__/schema.graphql.types.ts
frontend/src/components/PointsBar.tsx
frontend/src/components/StudentProfile/PointsForm/PointsForm.tsx
frontend/src/components/StudentProfile/cards/AnimalCard/AnimalCard.tsx
frontend/src/graphql/hallOfFame.graphql
frontend/src/graphql/hallOfFame.graphql.types.ts
frontend/src/graphql/studentPoints.graphql.types.ts
frontend/src/graphql/students.graphql.types.ts
frontend/src/hooks/Group/useStudentsSearchData.tsx
frontend/src/hooks/StudentProfile/useAnimalData.tsx
frontend/src/hooks/StudentProfile/useCategoriesCardData.tsx
frontend/src/hooks/StudentProfile/useStudentData.tsx
frontend/src/hooks/Students/useStudentsData.tsx
frontend/src/hooks/common/useGroupsData.tsx
frontend/src/screens/Group/Group.tsx

- delete fake data
- little undefined clean up
https://oops2000.atlassian.net/browse/SCRUM-106

[FE-106] Correct progress bar data

---

.gitignore
backend/src/main/kotlin/backend/graphql/EditionDataFetcher.kt
backend/src/main/python/config.json
backend/src/main/python/utils/insert_editions.py

Edition is editable when now() is after 01.10.20xx and before 30.09.20xx+1
Now the editable edition is edition with id=1, but in October it will be edition id=2

[122] Added an editable edition to the insert script

---

.gitignore
backend/src/main/kotlin/backend/BackendApplication.kt
backend/src/main/kotlin/backend/bonuses/Bonuses.kt
backend/src/main/kotlin/backend/graphql/BonusDataFetcher.kt
backend/src/main/kotlin/backend/graphql/GroupsDataFetcher.kt
backend/src/main/kotlin/backend/graphql/PointsDataFetcher.kt
backend/src/main/kotlin/backend/graphql/UsersDataFetcher.kt

Now Additive prev fills in gaps as much as it can.

[132] Reworked AdditivePrev without taking into account other awards

---

backend/src/main/python/config_from_gh.json
backend/src/main/python/utils/insert_subcategories.py

To generate realistic data change which file is loaded on top of the script

[139] Config like GH Soamid

---

backend/hasura/metadata/databases/mydatabase/tables/public_category_edition.yaml
backend/hasura/metadata/databases/mydatabase/tables/public_groups.yaml

Groups.teacher
not groups.userByTeacherId

[119] Fixed null teacher

---

backend/src/main/kotlin/backend/firebase/FirebaseUserService.kt
backend/src/main/kotlin/backend/graphql/UsersDataFetcher.kt
backend/src/main/kotlin/backend/userLevel/UserLevelRepository.kt
backend/src/main/kotlin/backend/users/UsersRepository.kt
backend/src/main/resources/schema/schema.graphql

add constants.emailDomain=example.oops.com
to application-secrets.properties

[164] Improved firebase user creation

---

backend/src/main/kotlin/backend/bonuses/Bonuses.kt
backend/src/main/kotlin/backend/graphql/PointsDataFetcher.kt

This fixes the User's levels issue

[170] Fixed updating bonuses when removing points

---

backend/hasura/metadata/databases/mydatabase/tables/public_users.yaml

[0] add missing email for coordinator

---

frontend/src/components/Edition/Sections/AwardsSection/AddAwardForm/AddAwardForm.tsx
frontend/src/components/Edition/Sections/AwardsSection/AwardsList/AwardCard.tsx
frontend/src/components/Edition/Sections/AwardsSection/AwardsList/AwardsList.tsx
frontend/src/components/Edition/Sections/AwardsSection/AwardsSection.tsx
frontend/src/components/Edition/Sections/CategoriesSection/AddCategoryForm/AddCategoryForm.tsx
frontend/src/components/Edition/Sections/CategoriesSection/CategoriesList/CategoriesList.tsx
frontend/src/components/Edition/Sections/CategoriesSection/CategoriesList/CategoryCard.tsx
frontend/src/components/Edition/Sections/CategoriesSection/CategoriesSection.tsx
frontend/src/components/Edition/Sections/FilesSection/FilesSection.tsx
frontend/src/components/Edition/Sections/SetupButtons.tsx
frontend/src/components/Groups/GroupsList/GroupCard.tsx
frontend/src/components/images/Image.tsx
frontend/src/components/inputs/SelectImage.tsx
frontend/src/graphql/setupAwardEdit.graphql
frontend/src/graphql/setupAwardEdit.graphql.types.ts
frontend/src/graphql/setupAwards.graphql
frontend/src/graphql/setupAwards.graphql.types.ts
frontend/src/graphql/setupCategories.graphql
frontend/src/graphql/setupCategories.graphql.types.ts
frontend/src/graphql/setupCategoryEdit.graphql
frontend/src/graphql/setupCategoryEdit.graphql.types.ts
frontend/src/hooks/Edition/categories/useCategoriesSection.tsx
frontend/src/hooks/Edition/useAwardsSection.tsx
frontend/src/hooks/common/useGlobalError.tsx
frontend/src/utils/constants.ts

https://oops2000.atlassian.net/browse/SCRUM-188
https://oops2000.atlassian.net/browse/SCRUM-189
https://oops2000.atlassian.net/browse/SCRUM-195
common:
- wrappers for local and global errors
awards section:
- add image select
categories:
- edit

[FE-188 FE-189 FE-195] Improve errors, categories and awards selctions

---

backend/hasura/metadata/databases/mydatabase/tables/public_levels.yaml
backend/src/main/kotlin/backend/BackendApplication.kt
backend/src/main/kotlin/backend/graphql/GroupsDataFetcher.kt
backend/src/main/kotlin/backend/graphql/LevelsDataFetcher.kt
backend/src/main/kotlin/backend/groups/Groups.kt
backend/src/main/kotlin/backend/groups/GroupsRepository.kt
backend/src/main/kotlin/backend/levels/Levels.kt
backend/src/main/kotlin/backend/levels/LevelsRepository.kt
backend/src/main/python/utils/insert_levels.py
backend/src/main/resources/db/migration/V53__add_level_set.sql
backend/src/main/resources/schema/schema.graphql
frontend/src/__generated__/schema.graphql
frontend/src/__generated__/schema.graphql.types.ts

```graphql
type LevelType {
levelId: ID!
levelName: String!
minimumPoints: String!
maximumPoints: String!
grade: String!
ordinalNumber: Int!
label: String!
edition: EditionType
levelSet: Int!
highest: Boolean!
imageFile: FileType
userLevels: [UserLevelType]
}
```
```graphql
input LevelInputType {
levelId: ID
name: String!,
maximumPoints: String!,
grade: String!,
imageFileId: ID
}
```
```graphql
type LevelSetType {
levelSetId: Int!,
editionId: ID,
levels: [LevelType!]!
}
```
```graphql
getLevelSets: [LevelSetType!]!
```
```graphql
addLevelSet(
levels: [LevelInputType!]!
): [LevelType!]!
```
```graphql
editLevelSet(
levelSet: Int!,
levels: [LevelInputType!]!
): [LevelType!]!
```
```graphql
removeLevelSet(
levelSet: Int!
): Boolean
```
```graphql
addLevelSetToEdition(
levelSet: Int! …
```

[214] Added levelSet to Levels

---

backend/hasura/metadata/databases/mydatabase/tables/public_edition.yaml
backend/hasura/metadata/databases/mydatabase/tables/public_level_sets.yaml
backend/hasura/metadata/databases/mydatabase/tables/public_levels.yaml
backend/hasura/metadata/databases/mydatabase/tables/tables.yaml
backend/src/main/kotlin/backend/BackendApplication.kt
backend/src/main/kotlin/backend/edition/Edition.kt
backend/src/main/kotlin/backend/graphql/GroupsDataFetcher.kt
backend/src/main/kotlin/backend/graphql/LevelSetDataFetcher.kt
backend/src/main/kotlin/backend/graphql/LevelsDataFetcher.kt
backend/src/main/kotlin/backend/graphql/PhotoAssigner.kt
backend/src/main/kotlin/backend/levelSet/LevelSet.kt
backend/src/main/kotlin/backend/levelSet/LevelSetRepository.kt
backend/src/main/kotlin/backend/levels/Levels.kt
backend/src/main/kotlin/backend/levels/LevelsRepository.kt
backend/src/main/python/insert_data.py
backend/src/main/python/utils/insert_levels.py
backend/src/main/resources/db/migration/V54__add_level_set_edition.sql
backend/src/main/resources/db/migration/V55__fix_user_level_trigger_level_set.sql
backend/src/main/resources/schema/schema.graphql

```graphql
type LevelType {
levelId: ID!
levelName: String!
minimumPoints: String!
maximumPoints: String!
grade: String!
ordinalNumber: Int!
label: String!
levelSet: LevelSetType!
highest: Boolean!
imageFile: FileType
userLevels: [UserLevelType!]!
}
```
```graphql
input LevelInputType {
levelId: ID
name: String!,
maximumPoints: String!,
grade: String!,
imageFileId: ID
}
```
```graphql
type LevelSetType {
levelSetId: ID!,
levelSetName: String!,
edition: [EditionType!]!
levels: [LevelType!]!
}
```
```graphql
query GetLevelSets {
levelSets {
levelSetId
edition {
editionId
}
levels {
levelId
name
}
}
}
```
```graphql
addLevelSet(
levels: [LevelInputType!]!
): LevelSetType!
```
```graphql
copyLevelSet(
levelSetId: Int!
): LevelSetType!
```
```graphql
editLevelSet(
levelSetId: Int!,
levels: …
```

[221] Added levelSet table

---

backend/src/main/kotlin/backend/graphql/PointsDataFetcher.kt
backend/src/main/kotlin/backend/points/PointsRepository.kt
backend/src/main/resources/schema/schema.graphql

```graphql
mutation MyMutation {
addPointsToGroup(groupId: 1, subcategoryId: 55, teacherId: 4, values: [{studentId: 15, value: null}, {studentId: 20, value: 2}, {studentId: 31, value: 4}, {studentId: 47, value: 5}, {studentId: 174, value: 9}, {studentId: 240, value: 2}, {studentId: 263, value: 2}, {studentId: 318, value: 2}, {studentId: 159, value: 2}, {studentId: 376, value: 2}, {studentId: 254, value: 2}, {studentId: 373, value: 2}, {studentId: 383, value: 2}, {studentId: 166, value: 3}, {studentId: 78, value: 6.2}, {studentId: 227, value: 2}]) {
student {
userId
}
points {
pointsId
}
}
}
```

[223] Added addPointsToGroup

---

backend/src/main/kotlin/backend/bonuses/BonusesRepository.kt
backend/src/main/kotlin/backend/graphql/GroupsDataFetcher.kt
backend/src/main/kotlin/backend/points/PointsRepository.kt
backend/src/main/kotlin/backend/users/UsersRepository.kt
backend/src/main/resources/schema/schema.graphql
frontend/src/__generated__/schema.graphql
frontend/src/__generated__/schema.graphql.types.ts
frontend/src/graphql/groupPoints.graphql
frontend/src/graphql/groupPoints.graphql.types.ts
frontend/src/hooks/Group/useGroupScreenData.tsx

```graphql
getUsersInGroupWithPoints(groupId: 13) {
user {
userId
}
categoriesPoints {
category {
categoryName
}
categoryAggregate {
category {
categoryId
}
sumOfAll
sumOfBonuses
sumOfPurePoints
}
awardAggregate {
award {
awardName
}
sumOfAll
}
subcategoryPoints {
subcategory {
subcategoryName
}
points {
value
}
createdAt
updatedAt
teacher {
userId
}
}
}
}
}
```

[210] Reworked getUsersInGroupWithPoints

---

backend/src/main/kotlin/backend/gradingChecks/GradingChecksRepository.kt
backend/src/main/kotlin/backend/graphql/partialPermissions/CategoryEditionPartialPermissions.kt
backend/src/main/kotlin/backend/graphql/permissions/CategoryEditionPermissions.kt
frontend/src/__generated__/schema.graphql
frontend/src/__generated__/schema.graphql.types.ts
frontend/src/components/Edition/Sections/GradingChecksSection/ChecksForm.tsx
frontend/src/components/Edition/Sections/GradingChecksSection/GradingChecksSection.tsx
frontend/src/components/Edition/SectionsBar.tsx
frontend/src/graphql/setupGradingChecks.graphql
frontend/src/graphql/setupGradingChecks.graphql.types.ts
frontend/src/graphql/setupGradingChecksAdd.graphql
frontend/src/graphql/setupGradingChecksAdd.graphql.types.ts
frontend/src/graphql/setupGradingChecksEdit.graphql
frontend/src/graphql/setupGradingChecksEdit.graphql.types.ts
frontend/src/hooks/Edition/useGradingChecksSection.tsx
frontend/src/router/paths.tsx
frontend/src/router/routes.tsx

https://oops2000.atlassian.net/browse/SCRUM-239

[FE-239] Grading check section

---

backend/hasura/metadata/databases/mydatabase/tables/public_users.yaml
backend/src/main/kotlin/backend/graphql/UsersDataFetcher.kt
backend/src/main/kotlin/backend/graphql/permissions/UsersPermissions.kt
backend/src/main/kotlin/backend/graphql/utils/PermissionService.kt
backend/src/main/kotlin/backend/users/Users.kt
backend/src/main/kotlin/backend/users/UsersRepository.kt
backend/src/main/resources/db/migration/V62__add_nick_set_by_user_flag_to_user.sql
backend/src/main/resources/schema/schema.graphql

```graphql
setStudentNick(
userId: Int!, nick: String!
): UserType
type UserType {
userId: ID!
nick: String!
role: UsersRolesType!
indexNumber: Int!
firstName: String!
secondName: String!
email: String!
active: Boolean!
nickSetByUser: Boolean!
avatarSetByUser: Boolean!
label: String!
firebaseUid: String
imageFile: FileType
userGroups: [UserGroupType]!
userLevels: [UserLevelType]!
points: [PointType]!
pointsByTeacher: [PointType]!
pointsByUpdatedBy: [PointType]!
pointsHistory: [PointsHistoryType]!
pointsHistoryByTeacher: [PointsHistoryType]!
groups: [GroupType]!
chestHistory: [ChestHistoryType]!
chestHistoryByTeacher: [ChestHistoryType]!
}
```

[260] Added setStudentNick

---

backend/src/main/kotlin/backend/graphql/UsersDataFetcher.kt
backend/src/main/kotlin/backend/graphql/permissions/UsersPermissions.kt
backend/src/main/kotlin/backend/graphql/utils/PermissionService.kt
backend/src/main/resources/schema/schema.graphql

```graphql
resetPasswordByEmail(email: String!): Boolean
```

[259] Added resetPasswordByEmail

---

backend/src/main/kotlin/backend/graphql/EditionDataFetcher.kt
backend/src/main/kotlin/backend/graphql/GradingChecksDataFetcher.kt
backend/src/main/kotlin/backend/graphql/partialPermissions/EditionPartialPermissions.kt
backend/src/main/kotlin/backend/graphql/permissions/GradingChecksPermissions.kt
backend/src/main/kotlin/backend/graphql/utils/PermissionService.kt
backend/src/main/resources/schema/schema.graphql

```graphql
type EditionWithPermissionsType{
edition: EditionType!,
permissions: ListPermissionsOutputType!
}
listSetupEditions: [EditionWithPermissionsType!]!
```

[250] Added canAdds for editions

---

backend/src/main/kotlin/backend/graphql/GradingChecksDataFetcher.kt
backend/src/main/kotlin/backend/graphql/partialPermissions/GradingChecksPartialPermissions.kt
backend/src/main/kotlin/backend/graphql/permissions/GradingChecksPermissions.kt
backend/src/main/kotlin/backend/graphql/utils/PermissionService.kt
backend/src/main/resources/schema/schema.graphql

```graphql
listSetupGradingChecks(
editionId: Int!
): GradingCheckWithPermissions!
type GradingCheckWithPermissions{
gradingCheck: GradingChecksType,
permissions: ListPermissionsOutputType!
}
```
GradingChecksType can be nullable

[256] Added listSetupGradingChecks

---

backend/src/main/kotlin/backend/graphql/FileDataFetcher.kt
backend/src/main/kotlin/backend/graphql/partialPermissions/FilePartialPermissions.kt
backend/src/main/kotlin/backend/graphql/utils/PermissionService.kt
backend/src/main/resources/schema/schema.graphql
frontend/src/__generated__/schema.graphql
frontend/src/__generated__/schema.graphql.types.ts
frontend/src/components/Edition/Sections/FilesSection/FilesSection.tsx
frontend/src/graphql/files.graphql
frontend/src/graphql/files.graphql.types.ts
frontend/src/hooks/Edition/useAwardsSection.tsx
frontend/src/hooks/Edition/useChestsSection.tsx
frontend/src/hooks/Edition/useLevelSetsSection.tsx

```graphql
removeFile(
fileId: Int!
): Boolean
type FileGroupType {
fileType: String!
files: [FileWithPermissions!]!
}
type FileWithPermissions{
file: FileType!,
permissions: ListPermissionsOutputType!
}
```

[261] Added removeFiles

---

frontend/src/hooks/Edition/categories/useCategoriesSection.tsx

https://oops2000.atlassian.net/browse/SCRUM-234

[FE-234] fix close category edit on confirm

---

frontend/src/__generated__/schema.graphql
frontend/src/__generated__/schema.graphql.types.ts
frontend/src/hooks/Edition/useAwardsSection.tsx

https://oops2000.atlassian.net/browse/SCRUM-211

[FE-211] Fix can add points field in add award form

---

frontend/src/components/CategoryTag.tsx
frontend/src/components/Group/GroupPointsForm.tsx
frontend/src/components/Group/PointsRow.tsx
frontend/src/components/Group/table/GroupTable.tsx
frontend/src/components/Group/table/GroupTableWithFilters.tsx
frontend/src/components/Groups/GroupsList/GroupsList.tsx
frontend/src/components/StudentProfile/table/StudentTable.tsx
frontend/src/graphql/addPointsToSubcategory.graphql
frontend/src/graphql/addPointsToSubcategory.graphql.types.ts
frontend/src/graphql/studentPoints.graphql
frontend/src/graphql/studentPoints.graphql.types.ts
frontend/src/hooks/Group/useGroupScreenData.tsx
frontend/src/hooks/Group/useGroupTableData.tsx
frontend/src/hooks/StudentProfile/useTeacherActions.tsx
frontend/src/router/paths.tsx
frontend/src/screens/Group/Group.tsx
frontend/src/screens/StudentProfile/TeacherStudentProfile.tsx

https://oops2000.atlassian.net/browse/SCRUM-199
https://oops2000.atlassian.net/browse/SCRUM-200
- add points to student
- add points to subcategory
- clean up in teacher actions hook
- add editable rights

[FE-199 FE-200] Enable adding points to group

---

backend/src/main/kotlin/backend/graphql/GroupsDataFetcher.kt
backend/src/main/kotlin/backend/graphql/permissions/PointsPermissions.kt
frontend/src/components/Group/table/GroupTable.tsx
frontend/src/components/Group/table/GroupTableWithFilters.tsx
frontend/src/graphql/groupPoints.graphql
frontend/src/graphql/groupPoints.graphql.types.ts
frontend/src/hooks/Group/useGroupScreenData.tsx
frontend/src/hooks/Group/useGroupTableData.tsx
frontend/src/hooks/common/useFormCategories.ts
frontend/src/screens/Group/Group.tsx
frontend/src/utils/utils.ts

https://oops2000.atlassian.net/browse/SCRUM-268
code is awful, but it works

[FE-268] Add missing columns to group table

---

frontend/src/__generated__/schema.graphql
frontend/src/__generated__/schema.graphql.types.ts
frontend/src/components/Edition/Sections/FilesSection/FilesSection.tsx
frontend/src/components/Edition/Sections/FilesSection/ImagesList/ImagesList.tsx
frontend/src/components/Edition/Sections/GradingChecksSection/ChecksForm.tsx
frontend/src/components/Edition/Sections/GradingChecksSection/GradingChecksSection.tsx
frontend/src/graphql/deleteFile.graphql
frontend/src/graphql/deleteFile.graphql.types.ts
frontend/src/graphql/files.graphql
frontend/src/graphql/files.graphql.types.ts
frontend/src/hooks/Edition/useGradingChecksSection.tsx
frontend/src/hooks/Edition/useLevelSetsSection.tsx

https://oops2000.atlassian.net/browse/SCRUM-248
https://oops2000.atlassian.net/browse/SCRUM-255

[FE-248 FE-255] Delete file, fix undefined levelSet error

---

frontend/src/contexts/userContext.tsx
frontend/src/hooks/auth/useLogin.tsx
frontend/src/hooks/useSettings.tsx
frontend/src/utils/types.ts

https://oops2000.atlassian.net/browse/SCRUM-275

[FE-275] Add selectedEdition to cookies

---

frontend/src/components/Edition/Sections/AwardsSection/AwardsSection.tsx
frontend/src/components/Group/table/GroupTable.tsx
frontend/src/components/Group/table/GroupTableWithFilters.tsx
frontend/src/components/StudentProfile/PointsForm/PointsForm.tsx
frontend/src/components/inputs/SelectInput.tsx
frontend/src/graphql/bonuses.graphql
frontend/src/graphql/bonuses.graphql.types.ts
frontend/src/hooks/Group/useGroupScreenData.tsx
frontend/src/hooks/StudentProfile/useStudentProfileData/useBonusesCardData.tsx
frontend/src/screens/Group/Group.tsx

- [GROUP] disable group table edit when edition is not active or no teacher has no editable rights
- [GROUP] add points to student error/refetch bug (?) https://oops2000.atlassian.net/browse/SCRUM-263
- [AWARDS SECTION] add award form 0.6 shows 0 https://oops2000.atlassian.net/browse/SCRUM-264
- [STUDENT PROFILE] awards card show bonus points fixed https://oops2000.atlassian.net/browse/SCRUM-262

[FE-263 FE-264 FE-262] Fix bugs

---

frontend/src/components/Edition/Sections/FilesSection/FilesSection.tsx
frontend/src/components/Navbar.tsx
frontend/src/contexts/confirmPopupContext.tsx
frontend/src/hooks/Edition/categories/useCategoriesSection.tsx
frontend/src/hooks/Edition/useAwardsSection.tsx
frontend/src/hooks/Edition/useChestsSection.tsx
frontend/src/hooks/Edition/useGroupsSection.tsx
frontend/src/hooks/Edition/useLevelSetsSection.tsx
frontend/src/hooks/Edition/users/useUsersSection.tsx
frontend/src/hooks/Editions/useEditionsScreen.tsx
frontend/src/hooks/StudentProfile/useTeacherActions.tsx
frontend/src/hooks/common/useConfrimPopup.ts
frontend/src/main.tsx

https://oops2000.atlassian.net/browse/SCRUM-233

[FE-233] Confrimation popup

---

backend/src/main/kotlin/backend/graphql/GroupsDataFetcher.kt
backend/src/main/resources/schema/schema.graphql

You can get all of the data needed (grades and whatnot) from userlevel

[281] Added userLevel to getusersingroupwithpoints

---

frontend/src/components/Edition/Sections/FilesSection/FilesSection.tsx
frontend/src/hooks/Edition/categories/useCategoriesSection.tsx
frontend/src/hooks/Edition/useAwardsSection.tsx
frontend/src/hooks/Edition/useChestsSection.tsx
frontend/src/hooks/Edition/useGradingChecksSection.tsx
frontend/src/hooks/Edition/useGroupsSection.tsx
frontend/src/hooks/Edition/useLevelSetsSection.tsx
frontend/src/hooks/Edition/users/useUsersSection.tsx

https://oops2000.atlassian.net/browse/SCRUM-282
It's a big slow... :(

[FE-282] Add no cache to edition sections

---

backend/hasura/metadata/databases/mydatabase/tables/public_chests.yaml
backend/src/main/kotlin/backend/chestEdition/ChestEdition.kt
backend/src/main/kotlin/backend/chestEdition/ChestEditionRepository.kt
backend/src/main/kotlin/backend/chests/Chests.kt
backend/src/main/kotlin/backend/graphql/ChestEditionDataFetcher.kt
backend/src/main/kotlin/backend/graphql/ChestsAwardDataFetcher.kt
backend/src/main/kotlin/backend/graphql/ChestsDataFetcher.kt
backend/src/main/kotlin/backend/graphql/partialPermissions/ChestEditionPartialPermissions.kt
backend/src/main/kotlin/backend/graphql/permissions/ChestEditionPermissions.kt
backend/src/main/kotlin/backend/graphql/permissions/ChestHistoryPermissions.kt
backend/src/main/kotlin/backend/graphql/permissions/ChestsAwardPermissions.kt
backend/src/main/kotlin/backend/graphql/utils/PermissionService.kt
backend/src/main/resources/db/migration/V65__add_active_to_chest_edition.sql
backend/src/main/resources/schema/schema.graphql
frontend/src/__generated__/schema.graphql
frontend/src/__generated__/schema.graphql.types.ts
frontend/src/graphql/setupChests.graphql
frontend/src/graphql/setupChests.graphql.types.ts
frontend/src/graphql/subscribeChestToOpen.graphql
frontend/src/graphql/subscribeChestToOpen.graphql.types.ts

```graphql
type ListPermissionsOutputType{
canAdd: PermissionType!
canEdit: PermissionType!
canCopy: PermissionType!
canRemove: PermissionType!
canSelect: PermissionType!
canUnselect: PermissionType!
additional: [PermissionType!]!
canOverride: PermissionType
canTurnOffOverride: PermissionType
canMarkAsActive: PermissionType
canMarkAsInactive: PermissionType
canActivate: PermissionType
canDeactivate: PermissionType
}
activateChestInEdition(
chestId: Int!
editionId: Int!
): Boolean
deactivateChestInEdition(
chestId: Int!
editionId: Int!
): Boolean
type ChestEditionType {
chestEditionId: ID!
chest: ChestType!
edition: EditionType!
active: Boolean!
label: String!
}
type ChestType {
chestId: ID!
chestType: String!
label: String!
awardBundleCount: Int!
chestHistory: [ChestHistoryType]! …
```

[290] Active in chestEdition

---

.devcontainer
.gitignore
backend/build.gradle.kts
backend/src/main/kotlin/backend/BackendApplication.kt
backend/src/main/kotlin/backend/firebase/FirebaseConfig.kt
backend/src/main/resources/application.properties
docker-compose.yaml
frontend/firebaseConfig.ts
frontend/vite.config.ts

Now all secrets are in .env in root

[0] Fixes to secrets

---

backend/src/main/kotlin/backend/graphql/GradingChecksDataFetcher.kt
backend/src/main/kotlin/backend/graphql/UsersDataFetcher.kt
backend/src/main/kotlin/backend/graphql/partialPermissions/LevelSetPartialPermissions.kt
backend/src/main/kotlin/backend/graphql/permissions/GradingChecksPermissions.kt
backend/src/main/kotlin/backend/graphql/permissions/LevelSetPermissions.kt
backend/src/main/kotlin/backend/graphql/permissions/UserGroupsPermissions.kt
backend/src/main/kotlin/backend/graphql/permissions/UsersPermissions.kt
backend/src/main/kotlin/backend/graphql/utils/PermissionService.kt
backend/src/main/kotlin/backend/levels/LevelsRepository.kt
backend/src/main/kotlin/backend/users/UsersRepository.kt
backend/src/main/resources/schema/schema.graphql

```graphql
getQuoteVariables(
editionId: Int!
): QuoteVariablesType!
type QuoteVariablesType{
firstPassingLevel: LevelType
gradingCheck: GradingChecksType
coordinator: UserType!
}
mutation MyMutation {
getQuoteVariables(editionId: 4) {
coordinator {
firstName
secondName
}
firstPassingLevel {
levelName
grade
}
gradingCheck {
endOfLabsDate
gradingCheckId
projectPointsThreshold
}
}
}
```

[299] Added getQuoteVariables

---

frontend/src/components/Edition/Sections/UsersSection/UsersSection.tsx
frontend/src/components/Editions/EditionsList/EditionCard.tsx
frontend/src/components/Students/StudentsListSearcher.tsx
frontend/src/components/layout/Navbar/ChestsNavbarItem.tsx
frontend/src/components/layout/Navbar/Navbar.tsx
frontend/src/hooks/auth/useLogin.tsx
frontend/src/screens/Group/GroupScreen.tsx
frontend/src/screens/StudentProfile/TeacherStudentProfile.tsx
frontend/src/screens/Students/StudentsScreen.tsx
frontend/src/utils/utils.ts

https://oops2000.atlassian.net/browse/SCRUM-302
https://oops2000.atlassian.net/browse/SCRUM-312
https://oops2000.atlassian.net/browse/SCRUM-324

[FE-302 FE-312 FE-324] small fixes

---

frontend/src/components/CustomButton.tsx
frontend/src/components/CustomIconButton.tsx
frontend/src/components/CustomText.tsx
frontend/src/components/Edition/Sections/AwardsSection/AddAwardForm/AddAwardForm.tsx
frontend/src/components/Edition/Sections/AwardsSection/AwardsSection.tsx
frontend/src/components/Edition/Sections/GradingChecksSection/ChecksForm.tsx
frontend/src/components/Edition/Sections/GradingChecksSection/GradingChecksSection.tsx
frontend/src/components/Edition/Sections/GroupSection/GroupAddForm.tsx
frontend/src/components/Edition/Sections/GroupSection/StudentSelection/SelectStudent.tsx
frontend/src/components/Edition/Sections/LevelsSection/AddSetForm/AddLevelForm.tsx
frontend/src/components/Edition/Sections/SetupButtons.tsx
frontend/src/components/Edition/Sections/UsersSection/StudentAddForm.tsx
frontend/src/components/FilterButton.tsx
frontend/src/components/IconMapper.tsx
frontend/src/components/Settings/ChangeEditionForm.tsx
frontend/src/components/Settings/Settings.tsx
frontend/src/components/StudentProfile/PointsForm/PointsForm.tsx
frontend/src/components/StudentProfile/cards/ChecksCard.tsx
frontend/src/components/StudentProfile/table/FilterMenu/FilterMenuItem.tsx
frontend/src/components/StudentProfile/table/StudentTable.tsx
frontend/src/components/avatars/AwardWithTooltip.tsx
frontend/src/components/dialogs/ChangeGroupDialog/ChangeGroupForm.tsx
frontend/src/components/dialogs/OverrideGradeDialog/OverrideGradeForm.tsx
frontend/src/components/hallOfFame/Podium/PodiumItem.tsx
frontend/src/hooks/Edition/useAwardsSection.tsx
frontend/src/hooks/Edition/users/useUsersSection.tsx
frontend/src/screens/StudentProfile/AddChestToUserForm.tsx
frontend/src/tokens.ts

https://oops2000.atlassian.net/browse/SCRUM-326
https://oops2000.atlassian.net/browse/SCRUM-327

[FE-326 FE-327] different fixes
